// Profile template definitions
// Each template provides styles for the profile page and mobile preview

export const TEMPLATES = [
    {
        id: "glass",
        name: "Liquid Glass",
        description: "Frosted glass with pink accents",
        category: "Influencer",
        font: "var(--font-sans)",
        animation: "tmpl-fadeSlideUp",
        preview: {
            bg: "linear-gradient(135deg, #f5f3fa 0%, #ede8f5 100%)",
            accent: "#e84393",
            cardBg: "rgba(255,255,255,0.3)",
        },
        styles: {
            page: {
                background: "linear-gradient(135deg, #f5f3fa 0%, #ede8f5 100%)",
                color: "#1a1a2e",
            },
            glow: "radial-gradient(ellipse at top, rgba(232,67,147,0.08) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(232,67,147,0.25)",
                boxShadow: "0 4px 16px rgba(232,67,147,0.15)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #e84393, #fd79a8)",
                color: "white",
            },
            name: { color: "#1a1a2e" },
            username: { color: "#6b6b8a" },
            bio: { color: "#9a9ab5" },
            linkCard: {
                background: "rgba(255,255,255,0.45)",
                border: "1px solid rgba(255,255,255,0.6)",
                backdropFilter: "blur(8px)",
                borderRadius: "14px",
                boxShadow: "inset 0 1px 0 rgba(255,255,255,0.5)",
            },
            linkText: { color: "#1a1a2e" },
            footer: { color: "#9a9ab5" },
        },
    },
    {
        id: "midnight",
        name: "Midnight",
        description: "Dark navy with neon accents",
        category: "DJ / Nightlife",
        font: "var(--font-space)",
        animation: "tmpl-fadeSlideUp",
        preview: {
            bg: "linear-gradient(135deg, #0a0a1a 0%, #141432 100%)",
            accent: "#00d4ff",
            cardBg: "rgba(0,212,255,0.1)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #0a0a1a 0%, #141432 50%, #0a0a1a 100%)",
                color: "#e0e0ff",
            },
            glow: "radial-gradient(ellipse at top, rgba(0,212,255,0.12) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(0,212,255,0.4)",
                boxShadow: "0 0 24px rgba(0,212,255,0.2)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #00d4ff, #0088cc)",
                color: "white",
            },
            name: { color: "#ffffff" },
            username: { color: "#8888cc" },
            bio: { color: "#7777aa" },
            linkCard: {
                background: "rgba(0,212,255,0.06)",
                border: "1px solid rgba(0,212,255,0.15)",
                backdropFilter: "blur(8px)",
                borderRadius: "12px",
                boxShadow: "0 0 12px rgba(0,212,255,0.05)",
            },
            linkText: { color: "#e0e0ff" },
            footer: { color: "#5555aa" },
        },
    },
    {
        id: "sunset",
        name: "Sunset Glow",
        description: "Warm orange and pink gradient",
        category: "Travel / Lifestyle",
        font: "var(--font-quicksand)",
        animation: "tmpl-scaleIn",
        preview: {
            bg: "linear-gradient(135deg, #ff9a56 0%, #ff6b8a 100%)",
            accent: "#fff",
            cardBg: "rgba(255,255,255,0.25)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #ff9a56 0%, #ff6b8a 50%, #c44569 100%)",
                color: "#ffffff",
            },
            glow: "radial-gradient(ellipse at top, rgba(255,255,255,0.15) 0%, transparent 60%)",
            avatar: {
                border: "3px solid rgba(255,255,255,0.5)",
                boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
            },
            avatarFallback: {
                background: "rgba(255,255,255,0.25)",
                color: "white",
            },
            name: { color: "#ffffff" },
            username: { color: "rgba(255,255,255,0.7)" },
            bio: { color: "rgba(255,255,255,0.6)" },
            linkCard: {
                background: "rgba(255,255,255,0.2)",
                border: "1px solid rgba(255,255,255,0.35)",
                backdropFilter: "blur(12px)",
                borderRadius: "16px",
                boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
            },
            linkText: { color: "#ffffff" },
            footer: { color: "rgba(255,255,255,0.5)" },
        },
    },
    {
        id: "forest",
        name: "Forest",
        description: "Deep green with earthy tones",
        category: "Eco / Wellness",
        font: "var(--font-cormorant)",
        animation: "tmpl-fadeSlideUp",
        preview: {
            bg: "linear-gradient(135deg, #1a3c2a 0%, #2d5a3f 100%)",
            accent: "#6bcb77",
            cardBg: "rgba(107,203,119,0.1)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #1a3c2a 0%, #234532 50%, #1a3c2a 100%)",
                color: "#d4e8d9",
            },
            glow: "radial-gradient(ellipse at top, rgba(107,203,119,0.08) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(107,203,119,0.35)",
                boxShadow: "0 4px 16px rgba(107,203,119,0.15)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #6bcb77, #4a9e5a)",
                color: "white",
            },
            name: { color: "#e8f5eb" },
            username: { color: "#7aaa85" },
            bio: { color: "#6a9a75" },
            linkCard: {
                background: "rgba(107,203,119,0.08)",
                border: "1px solid rgba(107,203,119,0.15)",
                backdropFilter: "blur(8px)",
                borderRadius: "14px",
                boxShadow: "0 1px 6px rgba(0,0,0,0.1)",
            },
            linkText: { color: "#d4e8d9" },
            footer: { color: "#5a8a65" },
        },
    },
    {
        id: "ocean",
        name: "Ocean Breeze",
        description: "Cool teal and aqua tones",
        category: "Surf / Fitness",
        font: "var(--font-nunito)",
        animation: "tmpl-slideRight",
        preview: {
            bg: "linear-gradient(135deg, #0f3057 0%, #00587a 100%)",
            accent: "#00b4d8",
            cardBg: "rgba(0,180,216,0.1)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #0f3057 0%, #00587a 50%, #0a2647 100%)",
                color: "#d0eef8",
            },
            glow: "radial-gradient(ellipse at top, rgba(0,180,216,0.1) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(0,180,216,0.35)",
                boxShadow: "0 4px 20px rgba(0,180,216,0.2)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #00b4d8, #0077b6)",
                color: "white",
            },
            name: { color: "#e8f6fc" },
            username: { color: "#7ab8cc" },
            bio: { color: "#6aa8bc" },
            linkCard: {
                background: "rgba(0,180,216,0.08)",
                border: "1px solid rgba(0,180,216,0.18)",
                backdropFilter: "blur(8px)",
                borderRadius: "14px",
                boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
            },
            linkText: { color: "#d0eef8" },
            footer: { color: "#5a98ac" },
        },
    },
    {
        id: "neon",
        name: "Neon Pop",
        description: "Black with vibrant neon glow",
        category: "Gamers / Streamers",
        font: "var(--font-space)",
        animation: "tmpl-scaleIn",
        preview: {
            bg: "linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%)",
            accent: "#39ff14",
            cardBg: "rgba(57,255,20,0.08)",
        },
        styles: {
            page: {
                background: "#0a0a0a",
                color: "#e0ffe0",
            },
            glow: "radial-gradient(ellipse at top, rgba(57,255,20,0.06) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(57,255,20,0.5)",
                boxShadow: "0 0 20px rgba(57,255,20,0.25), 0 0 40px rgba(57,255,20,0.1)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #39ff14, #20cc00)",
                color: "#0a0a0a",
            },
            name: { color: "#ffffff" },
            username: { color: "#39ff14" },
            bio: { color: "#888888" },
            linkCard: {
                background: "rgba(57,255,20,0.04)",
                border: "1px solid rgba(57,255,20,0.2)",
                backdropFilter: "none",
                borderRadius: "10px",
                boxShadow: "0 0 8px rgba(57,255,20,0.08), inset 0 0 8px rgba(57,255,20,0.03)",
            },
            linkText: { color: "#e0ffe0" },
            footer: { color: "#444444" },
        },
    },
    {
        id: "pastel",
        name: "Pastel Dream",
        description: "Soft pastel tones, ultra feminine",
        category: "Fashion / Beauty",
        font: "var(--font-quicksand)",
        animation: "tmpl-bounceIn",
        preview: {
            bg: "linear-gradient(135deg, #fce4ec 0%, #e8eaf6 100%)",
            accent: "#f48fb1",
            cardBg: "rgba(255,255,255,0.6)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #fce4ec 0%, #f3e5f5 40%, #e8eaf6 100%)",
                color: "#5a4a6a",
            },
            glow: "radial-gradient(ellipse at top, rgba(244,143,177,0.1) 0%, transparent 60%)",
            avatar: {
                border: "3px solid rgba(244,143,177,0.3)",
                boxShadow: "0 4px 16px rgba(244,143,177,0.15)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #f48fb1, #ce93d8)",
                color: "white",
            },
            name: { color: "#4a3a5a" },
            username: { color: "#9a8aaa" },
            bio: { color: "#8a7a9a" },
            linkCard: {
                background: "rgba(255,255,255,0.65)",
                border: "1px solid rgba(244,143,177,0.2)",
                backdropFilter: "blur(8px)",
                borderRadius: "20px",
                boxShadow: "0 2px 10px rgba(244,143,177,0.06)",
            },
            linkText: { color: "#4a3a5a" },
            footer: { color: "#b0a0c0" },
        },
    },
    {
        id: "minimal",
        name: "Minimal",
        description: "Clean white, ultra simple",
        category: "Entrepreneurs / Devs",
        font: "var(--font-sans)",
        animation: "tmpl-fadeIn",
        preview: {
            bg: "#ffffff",
            accent: "#333333",
            cardBg: "rgba(0,0,0,0.03)",
        },
        styles: {
            page: {
                background: "#ffffff",
                color: "#1a1a1a",
            },
            glow: "none",
            avatar: {
                border: "2px solid #e5e5e5",
                boxShadow: "none",
            },
            avatarFallback: {
                background: "#1a1a1a",
                color: "white",
            },
            name: { color: "#1a1a1a" },
            username: { color: "#999999" },
            bio: { color: "#666666" },
            linkCard: {
                background: "#f8f8f8",
                border: "1px solid #e8e8e8",
                backdropFilter: "none",
                borderRadius: "12px",
                boxShadow: "none",
            },
            linkText: { color: "#1a1a1a" },
            footer: { color: "#cccccc" },
        },
    },
    {
        id: "royal",
        name: "Royal Gold",
        description: "Dark luxury with gold accents",
        category: "Luxury / Premium",
        font: "var(--font-playfair)",
        animation: "tmpl-fadeSlideUp",
        preview: {
            bg: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
            accent: "#f0c040",
            cardBg: "rgba(240,192,64,0.08)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #1a1a2e 0%, #16213e 50%, #0f0f20 100%)",
                color: "#f0e6d0",
            },
            glow: "radial-gradient(ellipse at top, rgba(240,192,64,0.08) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(240,192,64,0.4)",
                boxShadow: "0 4px 20px rgba(240,192,64,0.15)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #f0c040, #d4a020)",
                color: "#1a1a2e",
            },
            name: { color: "#f0e6d0" },
            username: { color: "#c0a870" },
            bio: { color: "#9a8a6a" },
            linkCard: {
                background: "rgba(240,192,64,0.06)",
                border: "1px solid rgba(240,192,64,0.15)",
                backdropFilter: "blur(8px)",
                borderRadius: "14px",
                boxShadow: "0 2px 10px rgba(0,0,0,0.15)",
            },
            linkText: { color: "#f0e6d0" },
            footer: { color: "#6a5a4a" },
        },
    },
    {
        id: "candy",
        name: "Candy Pop",
        description: "Bright multicolor fun vibes",
        category: "Gen-Z / Fun",
        font: "var(--font-nunito)",
        animation: "tmpl-bounceIn",
        preview: {
            bg: "linear-gradient(135deg, #ff6ec7 0%, #7873f5 50%, #4cc9f0 100%)",
            accent: "#fff",
            cardBg: "rgba(255,255,255,0.2)",
        },
        styles: {
            page: {
                background: "linear-gradient(135deg, #ff6ec7 0%, #7873f5 50%, #4cc9f0 100%)",
                color: "#ffffff",
            },
            glow: "radial-gradient(ellipse at top, rgba(255,255,255,0.12) 0%, transparent 60%)",
            avatar: {
                border: "3px solid rgba(255,255,255,0.5)",
                boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
            },
            avatarFallback: {
                background: "rgba(255,255,255,0.25)",
                color: "white",
            },
            name: { color: "#ffffff" },
            username: { color: "rgba(255,255,255,0.75)" },
            bio: { color: "rgba(255,255,255,0.65)" },
            linkCard: {
                background: "rgba(255,255,255,0.18)",
                border: "1px solid rgba(255,255,255,0.3)",
                backdropFilter: "blur(12px)",
                borderRadius: "18px",
                boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
            },
            linkText: { color: "#ffffff" },
            footer: { color: "rgba(255,255,255,0.45)" },
        },
    },
    {
        id: "aurora",
        name: "Aurora",
        description: "Purple to green shimmer",
        category: "Artists / Photographers",
        font: "var(--font-cormorant)",
        animation: "tmpl-slideRight",
        preview: {
            bg: "linear-gradient(135deg, #2d1b69 0%, #11998e 100%)",
            accent: "#38ef7d",
            cardBg: "rgba(56,239,125,0.08)",
        },
        styles: {
            page: {
                background: "linear-gradient(180deg, #2d1b69 0%, #1a1050 30%, #11998e 100%)",
                color: "#d0f0e0",
            },
            glow: "radial-gradient(ellipse at top, rgba(56,239,125,0.08) 0%, transparent 60%)",
            avatar: {
                border: "2px solid rgba(56,239,125,0.35)",
                boxShadow: "0 0 20px rgba(56,239,125,0.15), 0 0 40px rgba(45,27,105,0.15)",
            },
            avatarFallback: {
                background: "linear-gradient(135deg, #38ef7d, #11998e)",
                color: "white",
            },
            name: { color: "#e8fff0" },
            username: { color: "#7ac0a0" },
            bio: { color: "#6ab090" },
            linkCard: {
                background: "rgba(56,239,125,0.06)",
                border: "1px solid rgba(56,239,125,0.15)",
                backdropFilter: "blur(8px)",
                borderRadius: "14px",
                boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
            },
            linkText: { color: "#d0f0e0" },
            footer: { color: "#5a9080" },
        },
    },
];

/**
 * Get template by ID, defaults to 'glass'
 */
export function getTemplate(templateId) {
    return TEMPLATES.find((t) => t.id === templateId) || TEMPLATES[0];
}
